services:
  pdf_generator:
    image: oberonamsterdam/wkhtmltopdf
    container_name: pdf_generator_container
    volumes:
      - ./templates/check:/templates
      - ./media/pdf:/media  
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: checks_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: