services:
  # pdf_generator:
  #   image: oberonamsterdam/wkhtmltopdf
  #   container_name: pdf_generator_container
  #   volumes:
  #     - ./templates/check:/templates
  #     - ./media/pdf:/media  
  #   ports:
  #     - "3000:3000"
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: checks_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_container 
    ports:
      - "6379:6379"

volumes:
  pg_data:
    