# Generated by Django 5.1.6 on 2025-03-11 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point.point'),
        ),
    ]
