# Generated by Django 5.1.6 on 2025-03-25 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_alter_printer_api_key'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_api_key.apikey'),
        ),
    ]
