# Generated by Django 5.1.6 on 2025-02-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=20)),
                ('order', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], max_length=20)),
                ('pdf', models.FileField(upload_to='media/pdf/')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printer')),
            ],
            options={
                'unique_together': {('order', 'printer', 'type')},
            },
        ),
    ]
