# Generated by Django 5.1.6 on 2025-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='number',
            field=models.CharField(default=0, max_length=14),
        ),
    ]
