# Generated by Django 5.1.6 on 2025-03-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_check_number_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='number_table',
            field=models.CharField(blank=True),
        ),
    ]
