# Generated by Django 5.1.6 on 2025-03-14 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_alter_check_number_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='check',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='check',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
